services:
  controller:
    image: jacobalberty/unifi
    init: true
    environment:
      - TZ=Europe/London
    ports:
      - "3478:3478/udp" # STUN
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "6789:6789/tcp" # Speed test
      - "10001:10001/udp" # AP discovery
    user: unifi
    volumes:
      - ./unifi/data:/unifi/data
      - ./unifi/log:/unifi/log
